name: autoSign

on:
  push:

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: chmod +x src/build.sh \
             | src/build.sh

      - name: Run example
        run: |
          docker run --rm \
            --env INPUT_REPO_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            pygithub src/sign_commit_using_github_api.py
